version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/java-projects/JtProject"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/python-projects/ai-lab"
    schedule:
      interval: "weekly"
