flowchart TD
    SCR06[SCR-06 管理者ログイン]
    SCR07[SCR-07 管理者ホーム]
    SCR08[SCR-08 カテゴリ管理]
    SCR09[SCR-09 商品管理一覧]
    SCR10[SCR-10 商品追加]
    SCR11[SCR-11 商品更新]
    SCR12[SCR-12 顧客一覧]
    SCR13[SCR-13 プロフィール更新]
    SCR03[SCR-03 商品トップ]

    SCR06 -->|認証成功| SCR07
    SCR07 --> SCR08
    SCR07 --> SCR09
    SCR07 --> SCR12
    SCR07 --> SCR13
    SCR09 -->|新規追加| SCR10
    SCR09 -->|更新| SCR11
    SCR10 -->|登録完了| SCR09
    SCR11 -->|更新完了| SCR09
    SCR13 -->|更新完了| SCR03