"""稳定错误码；客户端应依赖错误码而不是解析 message。"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """集中定义 API、Workflow 与 SSE 共用的机器可读错误分类。"""

    VALIDATION_ERROR = "VALIDATION_ERROR"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    INVALID_TASK_STATE = "INVALID_TASK_STATE"
    WORKFLOW_EXECUTION_ERROR = "WORKFLOW_EXECUTION_ERROR"
    RESEARCH_PROVIDER_ERROR = "RESEARCH_PROVIDER_ERROR"
    LOCAL_DATA_FILE_ERROR = "LOCAL_DATA_FILE_ERROR"
    REPORT_GENERATION_ERROR = "REPORT_GENERATION_ERROR"
    MISSING_TITLE = "missing_title"
    EMPTY_FILE = "empty_file"
    UNSUPPORTED_DOCUMENT_TYPE = "unsupported_document_type"
    INVALID_METADATA = "invalid_metadata"
    DUPLICATE_CHECKSUM = "duplicate_checksum"
    IDEMPOTENCY_CONFLICT = "idempotency_conflict"
    UPLOAD_TOO_LARGE = "upload_too_large"
    UNSUPPORTED_ENCODING = "unsupported_encoding"
    DOCUMENT_NOT_FOUND = "document_not_found"
    DOCUMENT_ARCHIVED = "document_archived"
    DOCUMENT_VERSION_CONFLICT = "document_version_conflict"
    REPOSITORY_ERROR = "repository_error"
    DATABASE_UNAVAILABLE = "database_unavailable"
    APPROVAL_REQUIRED = "approval_required"
    APPROVAL_REJECTED = "approval_rejected"
    RETRIEVAL_UNAVAILABLE = "retrieval_unavailable"
    PROVIDER_TIMEOUT = "provider_timeout"
    EVENT_PUBLISH_FAILED = "event_publish_failed"
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
